apiVersion: v1
kind: Pod
metadata:
  generateName: zephyr-ci-
  labels:
    app: zephyr-ci
  namespace: titan
spec:
  containers:
    - name: zephyr-builder
      image: forcedinductionz/ubuntu-zephyr:las16
      stdin: true
      tty: true
      env:
      - name: ZEPHYR_SOURCE
        value: SRC
      - name: ZEPHYR_BUILD_ID
        value: BUILD_ID
      - name: ZEPHYR_PLATFORM
        value: PLATFORM
      volumeMounts:
      - name: nfs
        mountPath: "/mnt/artifacts"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
  restartPolicy: Never
